name: fools_gold
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - backcall=0.2.0
  - blas=1.0
  - blas-devel=3.9.0
  - bzip2=1.0.8
  - ca-certificates=2021.1.19
  - certifi=2020.12.5
  - cpuonly=1.0
  - cycler=0.10.0
  - dbus=1.13.18
  - decorator=4.4.2
  - expat=2.3.0
  - ffmpeg=4.3
  - fontconfig=2.13.1
  - freetype=2.10.4
  - glib=2.68.0
  - gmp=6.2.1
  - gnutls=3.6.13
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - ipykernel=5.3.4
  - ipython=7.22.0
  - ipython_genutils=0.2.0
  - jedi=0.17.2
  - jpeg=9b
  - jupyter_client=6.1.12
  - jupyter_core=4.7.1
  - kiwisolver=1.3.1
  - lame=3.100
  - lcms2=2.11
  - ld_impl_linux-64=2.33.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=7.3.0
  - libiconv=1.16
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libpng=1.6.37
  - libsodium=1.0.18
  - libstdcxx-ng=9.1.0
  - libtiff=4.2.0
  - libuuid=1.0.3
  - libuv=1.41.0
  - libwebp-base=1.2.0
  - libxcb=1.14
  - libxml2=2.9.10
  - llvm-openmp=11.1.0
  - lz4-c=1.9.2
  - matplotlib=3.3.4
  - matplotlib-base=3.3.4
  - mkl=2020.4
  - mkl-devel=2020.4
  - mkl-include=2020.4
  - mkl-service=2.3.0
  - ncurses=6.2
  - nettle=3.6
  - ninja=1.10.2
  - numpy=1.20.2
  - olefile=0.46
  - openh264=2.1.1
  - openssl=1.1.1k
  - parso=0.7.0
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.1.2
  - pip=21.0.1
  - prompt-toolkit=3.0.17
  - ptyprocess=0.7.0
  - pygments=2.8.1
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - python=3.9.2
  - python-dateutil=2.8.1
  - python_abi=3.9
  - pytorch=1.8.1
  - pyzmq=20.0.0
  - qt=5.9.7
  - readline=8.1
  - scipy=1.6.2
  - setuptools=52.0.0
  - sip=4.19.13
  - six=1.15.0
  - sqlite=3.35.2
  - tk=8.6.10
  - torchaudio=0.8.1
  - torchvision=0.9.1
  - tornado=6.1
  - tqdm=4.59.0
  - traitlets=5.0.5
  - typing_extensions=3.7.4.3
  - tzdata=2020f
  - wcwidth=0.2.5
  - wheel=0.36.2
  - xz=5.2.5
  - zeromq=4.3.4
  - zlib=1.2.11
  - zstd=1.4.5